@startuml activity

start

if (Пользователь подписан?) then (да)
  :Вывод сообщения \n "Вы уже подписаны!";
else (нет)
  if (Вывод сообщения \n "Нажмите для \n оформления подписки") then (Нажал на кнопку)
    :Переадрессация на \nвеб-страницу \nплатежной системы ;
    if (Оплата прошла успешно?) then (да)
    :Вывод сообщения\n "Ура, подписка успешно оформлена!";
    else (нет)
    :Вывод сообщения\n "Не удалось оформить подписку";
    endif
  else (Пользователь закрыл окно)
    :Закрытие окна;
  endif
endif
stop
@enduml

